cluster:
  name: cortx-cluster
  id: <<.Values.cortx.cluster.id>>
  node_types:
  - name: storage_node
    components:
    - name: utils
    - name: motr
      services:
      - io
    - name: hare
    - name: s3
      services:
      - s3server
      - haproxy
      - authserver
      - bgworker
    storage:
    <<.Values.cluster.storage_list>>
  - name: control_node
    components:
    - name: utils
    - name: motr
      services:
      - fsm
    - name: s3
      services:
      - bgscheduler
    - name: csm
      services:
      - agent
  storage_sets:
  - name: <<.Values.cluster.storage_sets.name>>
    durability:
      sns: <<.Values.cluster.storage_sets.durability.sns>>
      dix: <<.Values.cluster.storage_sets.durability.dix>>
    nodes:
    <<.Values.cluster.storage_sets.nodes>>
